// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHu0YUfzPfIUHJUGOqimcZZ_-AMLnGm8',
    appId: '1:779499409047:web:093ac97b84b072332063d2',
    messagingSenderId: '779499409047',
    projectId: 'appointment-app4a',
    authDomain: 'appointment-app4a.firebaseapp.com',
    storageBucket: 'appointment-app4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUXY4r6HTx-IfbH4ee-L2YVCkW5yIiTto',
    appId: '1:779499409047:android:ee26647869a87fc32063d2',
    messagingSenderId: '779499409047',
    projectId: 'appointment-app4a',
    storageBucket: 'appointment-app4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANyCc3yHoZgo0X3F2nB1CD287dFSIG4BU',
    appId: '1:779499409047:ios:999b916cd76d9f9e2063d2',
    messagingSenderId: '779499409047',
    projectId: 'appointment-app4a',
    storageBucket: 'appointment-app4a.firebasestorage.app',
    iosBundleId: 'com.example.appointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANyCc3yHoZgo0X3F2nB1CD287dFSIG4BU',
    appId: '1:779499409047:ios:999b916cd76d9f9e2063d2',
    messagingSenderId: '779499409047',
    projectId: 'appointment-app4a',
    storageBucket: 'appointment-app4a.firebasestorage.app',
    iosBundleId: 'com.example.appointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoHu0YUfzPfIUHJUGOqimcZZ_-AMLnGm8',
    appId: '1:779499409047:web:7470be7c336f05a62063d2',
    messagingSenderId: '779499409047',
    projectId: 'appointment-app4a',
    authDomain: 'appointment-app4a.firebaseapp.com',
    storageBucket: 'appointment-app4a.firebasestorage.app',
  );
}
